### ISSUE TITLE
Los "no existe" son siempre 404

### ISSUE THREAD

**Issue by JJ** [Guillergood/DailyReport-2.0#83]
204 se usa normalmente para aclarar que no se devuelve nada en el body porque es la forma natural de hacerlo, para que el usuario no compruebe el body.

**Comment by Guillergood** [comment]
> 204 se usa normalmente para aclarar que no se devuelve nada en el body porque es la forma natural de hacerlo, para que el usuario no compruebe el body.
 Si, lo estoy viendo. ¿Esto es por lo que he puesto sobre las llamadas PUT, no? Gracias por el issue. Lo arreglaré enseguida.
